services:

  backend:
    container_name: chat-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file: ./backend/.env
    networks:
      - node-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: chat-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    restart: always
    networks:
      - node-network
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:stable-alpine
    container_name: chat-app-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
