services:

  backend:
    container_name: chat-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file: ./backend/.env
    networks:
      - node-network

  frontend:
    container_name: chat-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    restart: always
    networks:
      - node-network
    env_file: ./frontend/.env

  nginx:
    container_name: chat-app-nginx
    image: nginx:stable-alpine
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - node-network

  ngrok:
    container_name: chat-app-ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    volumes:
      - ./ngrok/ngrok.yaml:/ngrok.yaml
    ports:
      - 4040:4040
    command:
      - "start"
      - "default"
      - "--config"
      - "/ngrok.yaml"
      - "--log"
      - "stdout"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
