services:

  backend:
    container_name: chat-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file: ./backend/.env
    networks:
      - node-network

  frontend:
    container_name: chat-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    restart: always
    networks:
      - node-network
    env_file: ./frontend/.env

  nginx:
    image: nginx:stable-alpine
    container_name: chat-app-nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
