services:
  frontend:
    container_name: chat-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    restart: always
    env_file: ./frontend/.env
